"""Canonical context generation helpers for Cognitive Ledger."""

from __future__ import annotations

import datetime as dt
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ledger.notes import get_notes
from ledger.parsing import parse_timestamp, shorten


SCOPES = ("personal", "work", "dev")
ACTIVE_LOOP_STATUSES = {"open", "blocked", "snoozed"}
NOTE_TYPE_MAP = {
    "identity": "identity",
    "facts": "fact",
    "preferences": "preference",
    "goals": "goal",
    "loops": "loop",
}


@dataclass(frozen=True)
class ContextProfileItem:
    path: Path
    name: str
    type: str
    title: str
    summary: str
    updated: str
    updated_ts: dt.datetime | None
    confidence: float
    source: str
    scope: str
    status: str
    next_action: str
    score: float


def _render_list(lines: list[str], fallback_text: str) -> list[str]:
    if not lines:
        return [f"- {fallback_text}"]
    return lines


def canonical_scope(scope: str | None) -> str:
    lowered = str(scope or "").strip().lower()
    if lowered == "life":
        return "personal"
    return lowered


def source_weight(source: str | None) -> float:
    normalized = str(source or "").strip().lower()
    if normalized in {"user", "tool"}:
        return 1.0
    if normalized == "assistant":
        return 0.7
    if normalized == "inferred":
        return 0.6
    return 0.5


def recency_score(updated_ts: dt.datetime | None, now_dt: dt.datetime) -> float:
    if not updated_ts:
        return 0.0
    age_days = max(0.0, (now_dt - updated_ts).total_seconds() / 86400.0)
    return max(0.0, 1.0 - (age_days / 90.0))


def note_score(item: ContextProfileItem, now_dt: dt.datetime) -> float:
    recency = recency_score(item.updated_ts, now_dt)
    return (0.55 * recency) + (0.25 * item.confidence) + (0.20 * source_weight(item.source))


def build_context(notes_dir: Path) -> str:
    from ledger.config import get_config
    min_confidence = get_config().boot_min_confidence

    identity = get_notes("identity", notes_dir=notes_dir)
    facts = get_notes("facts", notes_dir=notes_dir)
    preferences = get_notes("preferences", notes_dir=notes_dir)
    goals = get_notes("goals", notes_dir=notes_dir)
    loops = get_notes("loops", notes_dir=notes_dir)

    # Filter boot context by confidence threshold
    identity = [n for n in identity if n.confidence >= min_confidence]
    facts = [n for n in facts if n.confidence >= min_confidence]
    preferences = [n for n in preferences if n.confidence >= min_confidence]
    goals = [n for n in goals if n.confidence >= min_confidence]

    active_loops = [note for note in loops if (note.status or "open") in ACTIVE_LOOP_STATUSES]
    all_notes = identity + facts + preferences + goals + loops
    all_updated = [note.updated for note in all_notes if note.updated]
    latest_update = max(all_updated) if all_updated else "unknown"

    identity_lines = [
        f"- `{note.path.name}` - {shorten(note.statement or note.title, 160)}"
        for note in identity
    ]
    fact_lines = [
        f"- `{note.path.name}` - {shorten(note.statement or note.title, 160)}"
        for note in facts[:6]
    ]
    preference_lines = [
        f"- `{note.path.name}` - {shorten(note.statement or note.title, 160)}"
        for note in preferences[:8]
    ]
    loop_lines = [
        (
            f"- `{note.path.name}` ({note.status or 'open'}) - "
            f"{shorten(note.question or note.title, 120)}; "
            f"next: {shorten(note.next_action or 'next action not set', 100)}"
        )
        for note in active_loops[:12]
    ]

    output = [
        "# Ledger Context (Boot Summary)",
        "",
        "Auto-generated by `./scripts/sheep index`. Edit source notes; do not edit this file directly.",
        "",
        "## Snapshot",
        "",
        f"- Identity: {len(identity)}",
        f"- Facts: {len(facts)}",
        f"- Preferences: {len(preferences)}",
        f"- Goals: {len(goals)}",
        f"- Active loops: {len(active_loops)}",
        f"- Latest source update: {latest_update}",
        "",
    ]

    if identity_lines:
        output.extend([
            "## Identity",
            "",
            *identity_lines,
            "",
        ])

    output.extend([
        "## Key Facts",
        "",
        *_render_list(fact_lines, "No facts available."),
        "",
        "## Key Preferences",
        "",
        *_render_list(preference_lines, "No preferences available."),
        "",
        "## Active Open Loops",
        "",
        *_render_list(loop_lines, "No active loops."),
        "",
        "## When to Search Deeper",
        "",
        "Before responding about:",
        "- Identity, mission, beliefs, strategies -> search `notes/01_identity/`",
        "- Personal details, history, family -> search `notes/02_facts/`",
        "- Past decisions or commitments -> search `notes/02_facts/` and `notes/08_indices/timeline.md`",
        "- User preferences or style -> search `notes/03_preferences/`",
        "- Ongoing threads or open questions -> search `notes/05_open_loops/`",
        "- Defined concepts or frameworks -> search `notes/06_concepts/`",
        "",
        "Rule: if about to guess or assume something about the user, search first.",
        "",
    ])
    return "\n".join(output)


def collect_profile_items(notes_dir: Path) -> list[ContextProfileItem]:
    now_dt = dt.datetime.now(tz=dt.timezone.utc)
    rows: list[ContextProfileItem] = []

    for note_type_name, note_type in NOTE_TYPE_MAP.items():
        for note in get_notes(note_type_name, notes_dir=notes_dir):
            summary = getattr(note, "statement", "")
            status = ""
            next_action = ""
            if note_type == "loop":
                summary = note.question
                status = note.status or "open"
                next_action = note.next_action

            item = ContextProfileItem(
                path=note.path,
                name=note.path.name,
                type=note_type,
                title=note.title or note.path.stem.replace("_", " "),
                summary=summary,
                updated=note.updated,
                updated_ts=parse_timestamp(note.updated),
                confidence=note.confidence,
                source=note.frontmatter.source.value if hasattr(note.frontmatter, "source") else "",
                scope=canonical_scope(note.scope),
                status=status,
                next_action=next_action,
                score=0.0,
            )
            rows.append(
                ContextProfileItem(
                    path=item.path,
                    name=item.name,
                    type=item.type,
                    title=item.title,
                    summary=item.summary,
                    updated=item.updated,
                    updated_ts=item.updated_ts,
                    confidence=item.confidence,
                    source=item.source,
                    scope=item.scope,
                    status=item.status,
                    next_action=item.next_action,
                    score=note_score(item, now_dt),
                )
            )

    return rows


def render_profile(scope: str, items: list[ContextProfileItem]) -> tuple[str, dict[str, Any]]:
    scope_items = [item for item in items if item.scope == scope]

    # Identity notes appear in every profile (they're scope-independent)
    identity = sorted(
        (item for item in items if item.type == "identity"),
        key=lambda item: item.score, reverse=True,
    )
    facts = sorted((item for item in scope_items if item.type == "fact"), key=lambda item: item.score, reverse=True)[:6]
    preferences = sorted(
        (item for item in scope_items if item.type == "preference"),
        key=lambda item: item.score,
        reverse=True,
    )[:8]
    loops = sorted(
        (
            item
            for item in scope_items
            if item.type == "loop" and item.status in ACTIVE_LOOP_STATUSES and item.next_action
        ),
        key=lambda item: item.score,
        reverse=True,
    )[:10]

    lines = [
        f"# Context Profile ({scope})",
        "",
        "Auto-generated by `./scripts/sheep index`. Edit source notes; do not edit this file directly.",
        "",
        "## Snapshot",
        "",
        f"- Scope: {scope}",
        f"- Identity: {len(identity)}",
        f"- Facts: {len(facts)}",
        f"- Preferences: {len(preferences)}",
        f"- Active loops with next action: {len(loops)}",
        "",
    ]

    if identity:
        lines.extend(["## Identity", ""])
        lines.extend(f"- `{item.name}` - {shorten(item.summary, 160)}" for item in identity)
        lines.append("")

    lines.extend(["## Top Facts", ""])
    if facts:
        lines.extend(f"- `{item.name}` - {shorten(item.summary, 160)}" for item in facts)
    else:
        lines.append("- No scope-matching facts found.")

    lines.extend(["", "## Top Preferences", ""])
    if preferences:
        lines.extend(f"- `{item.name}` - {shorten(item.summary, 160)}" for item in preferences)
    else:
        lines.append("- No scope-matching preferences found.")

    lines.extend(["", "## Active Open Loops", ""])
    if loops:
        lines.extend(
            (
                f"- `{item.name}` ({item.status}) - {shorten(item.summary, 120)}; "
                f"next: {shorten(item.next_action, 100)}"
            )
            for item in loops
        )
    else:
        lines.append("- No active scope-matching loops with explicit next action.")

    lines.extend(
        [
            "",
            "## When to Search Deeper",
            "",
            "Before responding:",
            f"- Start with this profile: `notes/08_indices/context_profile_{scope}.md`",
            "- Expand to canonical notes via `./scripts/ledger query \"<topic>\" --scope <scope>`",
            "- Verify critical claims in source notes before committing to an answer",
            "",
        ]
    )

    def _payload_row(item: ContextProfileItem) -> dict[str, Any]:
        path_str = str(item.path)
        home = str(Path.home())
        if path_str.startswith(home + "/"):
            path_str = "~" + path_str[len(home):]
        return {
            "path": path_str,
            "title": item.title,
            "summary": item.summary,
            "score": round(item.score, 6),
            "updated": item.updated,
            "confidence": item.confidence,
            "source": item.source,
        }

    payload = {
        "scope": scope,
        "identity": [_payload_row(item) for item in identity],
        "facts": [_payload_row(item) for item in facts],
        "preferences": [_payload_row(item) for item in preferences],
        "active_loops": [
            {
                **_payload_row(item),
                "status": item.status,
                "next_action": item.next_action,
            }
            for item in loops
        ],
    }
    return "\n".join(lines) + "\n", payload


def write_context(output_path: Path, notes_dir: Path) -> None:
    from ledger.io import safe_write_text

    output_path.parent.mkdir(parents=True, exist_ok=True)
    safe_write_text(output_path, build_context(notes_dir), use_lock=False)


def write_context_profiles(output_dir: Path, notes_dir: Path) -> None:
    from ledger.io import safe_write_text

    output_dir.mkdir(parents=True, exist_ok=True)
    items = collect_profile_items(notes_dir)
    for scope in SCOPES:
        markdown, payload = render_profile(scope, items)
        safe_write_text(output_dir / f"context_profile_{scope}.md", markdown, use_lock=False)
        safe_write_text(
            output_dir / f"context_profile_{scope}.json",
            json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
            use_lock=False,
        )
