"""Voice DNA integration for Cognitive Ledger.

Import, export, and retrieve a voice-dna-creator profile stored
as an identity note in the ledger.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ledger.config import get_config
from ledger.io.safe_write import safe_write_text, append_timeline_entry
from ledger.parsing.frontmatter import parse_frontmatter_text, serialize_frontmatter


VOICE_NOTE_FILENAME = "id__voice_dna.md"


def _voice_note_path(notes_dir: Path | None = None) -> Path:
    config = get_config()
    nd = notes_dir or config.notes_dir
    return nd / "01_identity" / VOICE_NOTE_FILENAME


def import_voice_dna(
    json_path: str | Path,
    notes_dir: Path | None = None,
) -> Path:
    """Import a voice-dna JSON file as an identity note.

    Args:
        json_path: Path to the voice-dna JSON file.
        notes_dir: Optional notes directory override.

    Returns:
        Path to the created/updated identity note.

    Raises:
        FileNotFoundError: If json_path does not exist.
        ValueError: If the JSON is invalid.
    """
    json_path = Path(json_path)
    if not json_path.is_file():
        raise FileNotFoundError(f"Voice DNA file not found: {json_path}")

    raw = json_path.read_text(encoding="utf-8")
    try:
        profile = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in voice DNA file: {exc}") from exc

    if not isinstance(profile, dict):
        raise ValueError("Voice DNA must be a JSON object")

    now = datetime.now(timezone.utc)
    ts = now.strftime("%Y-%m-%dT%H:%M:%SZ")

    dest = _voice_note_path(notes_dir)
    is_update = dest.is_file()

    if is_update:
        existing_fm, _ = parse_frontmatter_text(dest.read_text(encoding="utf-8"))
        created = str(existing_fm.get("created", ts))
    else:
        created = ts

    fm = {
        "created": created,
        "updated": ts,
        "tags": ["voice", "identity", "writing-style"],
        "confidence": 0.9,
        "source": "tool",
        "scope": "meta",
        "lang": "en",
        "identity_type": "voice",
    }

    profile_json = json.dumps(profile, indent=2, ensure_ascii=False)

    body = f"""
# Voice DNA

## Statement
Writing voice profile captured from analyzed samples.

## Voice Profile

```json
{profile_json}
```

## Context
Generated by the voice-dna-creator skill. Agents should read this note
before writing any note longer than 2 sentences and apply the voice
profile to tone, sentence structure, and vocabulary.

## Links
"""

    content = serialize_frontmatter(fm) + body.lstrip("\n")
    dest.parent.mkdir(parents=True, exist_ok=True)
    safe_write_text(dest, content)

    config = get_config()
    action = "updated" if is_update else "created"
    append_timeline_entry(
        config.timeline_path,
        action,
        dest,
        f"voice DNA {'updated' if is_update else 'imported'} from {json_path.name}",
        root_dir=config.root_dir,
    )

    return dest


def export_voice_dna(notes_dir: Path | None = None) -> dict[str, Any] | None:
    """Export the voice DNA profile as a dict.

    Returns:
        The parsed JSON profile, or None if no voice note exists.
    """
    dest = _voice_note_path(notes_dir)
    if not dest.is_file():
        return None

    text = dest.read_text(encoding="utf-8")
    _, body = parse_frontmatter_text(text)

    # Extract JSON from fenced code block
    in_block = False
    json_lines: list[str] = []
    for line in body.splitlines():
        if line.strip().startswith("```json") and not in_block:
            in_block = True
            continue
        if line.strip().startswith("```") and in_block:
            break
        if in_block:
            json_lines.append(line)

    if not json_lines:
        return None

    try:
        return json.loads("\n".join(json_lines))
    except json.JSONDecodeError:
        return None


def get_voice_profile(notes_dir: Path | None = None) -> dict[str, Any] | None:
    """Return the parsed voice profile or None.

    Convenience alias for export_voice_dna().
    """
    return export_voice_dna(notes_dir)
